version : '2'
services:
  peer1.orgprocess.trace.com:  #同上
    container_name: peer1.orgprocess.trace.com
    image: hyperledger/fabric-peer:latest  
    environment:    #环境变量
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=trace_default  # 修改
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_GOSSIP_USELEADERELECTION=true  #是否使用自动选举，此处选择true,自动选举，下面就设置为false
      - CORE_PEER_GOSSIP_ORGLEADER=false        #是否不是leader节点
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_LOCALMSPID=OrgProcessMSP
      - CORE_PEER_ID=peer1.orgprocess.trace.com              #当前peer节点的名字
      - CORE_PEER_ADDRESS=peer1.orgprocess.trace.com:7051    #当前节点的地址信息
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.orgprocess.trace.com:7051        #启动节点后向节点发起gossip链接，以加入网络
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.orgprocess.trace.com:7051 #节点被“组织外“节点感知时的地址，默认为空,代表不被其他组织节点所感知
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/orgprocess.trace.com/peers/peer1.orgprocess.trace.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/orgprocess.trace.com/peers/peer1.orgprocess.trace.com/tls:/etc/hyperledger/fabric/tls
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer     #peer节点启动之后的工作目录
    command: peer node start     #peer节点启动执行的命令
    networks:
     default:
      aliases:
      - trace
    ports:
      - 8051:7051
      - 8053:7053 # 事件的端口
